#!/bin/bash
# eyeball v0.1

EYEBALL_VERSION=0.1

if [ "--version" == "$1" ]; then
  echo eyeball $EYEBALL_VERSION
  exit 0
fi

if [ "--update" == "$1" ]; then
  # Update the expected output by replacing <outputfile> with <outputfile>.eyeball
  if [ "$#" -ne 2 ]; then
    echo "Usage: eyeball --update <outputfile>"
    exit 1
  fi

  FILE=$2
  EXPECTED_FILE=$FILE
  ACTUAL_FILE=$FILE.eyeball

  if [ ! -f $ACTUAL_FILE ]; then
    echo "$ACTUAL_FILE does not exist. Nothing to do."
    exit 1
  fi

  rm $EXPECTED_FILE
  mv $ACTUAL_FILE $EXPECTED_FILE
  echo "Updated $EXPECTED_FILE and deleted $ACTUAL_FILE"
  exit 0
fi

if [ "$#" -ne 2 ]; then
    echo "Usage: eyeball <program> <outputfile>"
    exit 1
fi

COMMAND=$1
FILE=$2
EXPECTED_FILE=$FILE
ACTUAL_FILE=$FILE.eyeball

if [[ -n "$EYEBALL_DIFF" ]]; then
    DIFF=$EYEBALL_DIFF
elif hash git 2>/dev/null; then
    DIFF="git --no-pager diff --color-words --no-index"
else
    DIFF="diff"
fi

DIFF_COMMAND_LINE="$DIFF $EXPECTED_FILE $ACTUAL_FILE"

# Run the command and output to the 'expected' file if it doesn't already exist, then exit
if [ ! -f $EXPECTED_FILE ]; then
    eval $COMMAND 2>&1 | tee $EXPECTED_FILE
    echo ">>> eyeball: Created '$EXPECTED_FILE'"
    exit 0
fi

# Run the command and output to the 'actual' file
$COMMAND 2>&1 | tee $ACTUAL_FILE 

ACTUAL_FILE_LINES=$(cat $ACTUAL_FILE | wc -l | xargs)
EXPECTED_FILE_LINES=$(cat $EXPECTED_FILE | wc -l | xargs)

# Don't show diff if actual output line count is less than a tenth of expected output line count
if [ $EXPECTED_FILE_LINES -ne 0 ] ; then
  let TOO_FEW_OUTPUT_LINES=`bc <<< "scale=100; ($ACTUAL_FILE_LINES / $EXPECTED_FILE_LINES) < 0.1"`
  if [ $TOO_FEW_OUTPUT_LINES == 1 ] ; then
    echo ">>> eyeball: Output much shorter than expected (expected $EXPECTED_FILE_LINES lines, saw $ACTUAL_FILE_LINES lines). Not showing diff."
    echo ">>> eyeball: To see the diff run '$DIFF_COMMAND_LINE'"
    echo ">>> eyeball: Run 'eyeball --update $2' to update expected output."
    echo ">>> eyeball: FAIL"
    exit 1
  fi
fi

echo ">>> eyeball: Running '$DIFF_COMMAND_LINE'"
$DIFF_COMMAND_LINE
DIFF_EXIT_CODE=$?

if [ $DIFF_EXIT_CODE == 0 ] ; then
  echo ">>> eyeball: Output matches $EXPECTED_FILE"
  echo ">>> eyeball: PASS"
  rm $ACTUAL_FILE
else
  echo ">>> eyeball: Output does not match $EXPECTED_FILE"
  echo ">>> eyeball: If you want to accept these changes, run 'eyeball --update $FILE'"
  echo ">>> eyeball: FAIL"
  exit 1
fi